### ISSUE TITLE
Creación de la interfaz

### ISSUE THREAD

**Issue by JuanpaAG14** [OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA#17]
Se creará la interfaz gráfica a partir del diseño asignado en el apartado de diseño de interfaz gráfica

**Comment by OmarBravo26** [comment]
Ese Oscar no chambea

**Comment by ohmCX23** [comment]
Como no

**Comment by ohmCX23** [comment]
![Actualizar usuario](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/38f42206-3561-4c07-ae58-c076f55882b7)
![Consultar](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/2b81458c-4a2a-47e6-8134-4d4c60fb792a)
![Interfaz Login](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/fa88c100-3f9f-4d10-8875-b3bd4d706a69)
![Menu](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/81172729-090c-440b-8714-a554a5290642)
![Registrar Invitado](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/efba74cd-d7ae-4508-af9a-6881f4cee48f)
![Registrar Usuario](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/b77e6aee-b625-452f-8413-109d0b4f7923)
![Ventana Eliminar](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/75181172-572c-4173-b45a-14c56deb840b)
![Ventana Info User](https://github.com/OmarBravo26/-Proyecto-Sistema-de-control-para-acceso-a-un-estacionamiento-CSA/assets/159394778/b4b1ab3f-4ce6-4997-85f4-6ec4322ace5d)
